version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  -
    source: /target/wtc-backend-api.jar
    destination: /home/ubuntu/app/prod/deploy
  -
    source: /target/wtc-backend-cli.jar
    destination: /home/ubuntu/app/prod/deploy
  -
    source: /frontend/dist
    destination: /home/ubuntu/app/prod/f-deploy
  -
    source: swap_release.sh
    destination: /home/ubuntu/app/prod
  -
    source: post_deploy_bg.sh
    destination: /home/ubuntu/app/prod

hooks:
  AfterInstall:
    -
      location: post_deploy.sh
      timeout: 300
      runas: root