version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 14
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install -P api
      - mvn install -P cli
      - cd frontend && npm i && npm run build && cd ..
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/wtc-backend-cli.jar
    - target/wtc-backend-api.jar
    - frontend/dist/**/*
    - appspec.yml
    - post_deploy.sh
    - post_deploy_bg.sh
    - swap_release.sh
    - notification.sh