version: '3.7'
services:
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"