-
  hosts: master1
  become: true
  tasks:
    -
      name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ruby
          - nginx
          - openjdk-11-jre-headless
    -
      name: Download Code deploy agent
      get_url:
        url: https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
        dest: /tmp
        mode: +x
    -
      name: Install code deploy agent
      command: /tmp/install auto
    -
      name: Install cert bot
      snap:
        name: certbot
        classic: yes
    -
      name: Create folders for releases
      file:
        path: '/home/ubuntu/app/prod/{{ item }}'
        state: directory
      loop:
        - blue
        - green
        - deploy
        - nginx
        - f-blue
        - f-green
        - f-deploy
    -
      name: Copy environment variables
      copy:
        src: './{{ item }}'
        dest: /home/ubuntu/app/env
        owner: root
        group: root
      loop:
        - .env
        - .env_test
    -
      name: Copy Nginx configuration
      copy:
        src: ../nginx/default
        dest: /etc/nginx/sites-enabled
        owner: root
        group: root
    -
      name: Copy Nginx blue-green configuration
      copy:
        src: '../nginx/{{ item }}'
        dest: /home/ubuntu/app/prod/nginx
        owner: root
        group: root
      loop:
        - blue
        - green
    -
      name: Copy Services
      copy:
        src: '../service/{{ item }}.service'
        dest: /etc/systemd/system
        owner: root
        group: root
      loop:
        - blue-wtc
        - blue-wtc-f
        - green-wtc
        - green-wtc-f
    -
      name: Download nvm
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
        dest: /tmp
        mode: +x
    -
      name: Install nvm
      command: bash /tmp/install.sh
    -
      name: Install NodeJS 14
      shell: "{{ item }}"
      with_items:
        - export NVM_DIR="$HOME/.nvm"
        - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
        - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
        - nvm install 14.17.4
        - ln -sf /home/ubuntu/.nvm/versions/node/v14.17.4/bin/node /usr/local/bin/node
      args:
        executable: /bin/bash