-
  hosts: master1
  become: true
  tasks:
    -
      name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ruby
          - nginx
          - openjdk-11-jre-headless
    -
      name: Download Code deploy agent
      get_url:
        url: https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
        dest: /tmp
        mode: +x
    -
      name: Install code deploy agent
      command: /tmp/install auto
    -
      name: Install cert bot
      snap:
        name: certbot
        classic: yes
    -
      name: Create folders for releases
      file:
        path: '/home/ubuntu/app/prod/{{ item }}'
        state: directory
      loop:
        - blue
        - green
        - deploy
    -
      name: Copy environment variables
      copy:
        src: .env
        dest: /home/ubuntu/app/prod
        owner: root
        group: root
    -
      name: Copy Nginx configuration
      copy:
        src: ../nginx/default
        dest: /etc/nginx/sites-enabled
        owner: root
        group: root
    -
      name: Copy Services
      copy:
        src: ../service/green-wtc.service
        dest: /etc/systemd/system
        owner: root
        group: root