-
  hosts: master1
  become: true
  tasks:
    -
      name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ruby
          - nginx
          - openjdk-11-jre-headless
    -
      name: Install code deploy agent
      command: "{{ item }}"
      with_items:
        - wget -P /tmp https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
        - chmod +x /tmp/install
        - /tmp/install auto
    -
      name: Create folders for releases
      file:
        path: '/home/ubuntu/app/prod/{{ item }}'
        state: directory
      loop:
        - blue
        - green
        - deploy
    -
      name: Copy environment variables
      copy:
        src: .env
        dest: /home/ubuntu/app/prod
        owner: root
        group: root