-
  name: Copy environment variables
  copy:
    src: '../../environment/{{ env_file }}'
    dest: '{{ working_directory }}/env'
    owner: root
    group: root
  loop_control:
    loop_var: env_file
  loop:
    - .env
    - .env_test