- name: Create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: ~/go-sdk

- name: Download Go SDK
  get_url:
    url: 'https://storage.googleapis.com/golang/go1.19.linux-amd64.tar.gz'
    dest: ~/go-sdk/go.tar.gz
    force: no
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: Unpack Go SDK
  unarchive:
    src: ~/go-sdk/go.tar.gz
    remote_src: yes
    dest: ~/go-sdk

- name: Update PATH
  lineinfile:
    path: ~/.bashrc
    line: export PATH="$PATH:~/go-sdk/go/bin"
