-
  name: Copy Nginx configuration
  copy:
    src: ../../nginx/default
    dest: /etc/nginx/sites-enabled
    owner: root
    group: root
-
  name: Copy Nginx blue-green configuration
  copy:
    src: '../../nginx/{{ item }}'
    dest: '{{ working_directory }}/nginx'
    owner: root
    group: root
  loop:
    - blue
    - green