- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 16.17 && nvm alias default 16.17"
    creates=/home/{{ ansible_user_id }}/.nvm/alias