-
  hosts: prod
  become: true
  tasks:
    -
      name: Init prod
      include_tasks: '../tasks/{{ item }}.yml'
      loop:
        - dependencies_install
        - releases_init
        - environment_copy
        - nginx_config_copy
        - services_config_copy
        - node_install
