-
  hosts: prod
  become: true
  tasks:
    -
      name: Copy crons
      copy:
        src: ../../crontab/cron
        dest: '{{ working_directory }}/cron'
        owner: root
        group: root
    -
      name: Start crons
      shell: '{{ item }}'
      with_items:
        - 'dos2unix {{ working_directory }}/cron/cron && crontab {{ working_directory }}/cron/cron'
        - echo PATH=$PATH > /etc/environment
        - 'cat {{ working_directory }}/env/.env >> /etc/environment'