-
  hosts: master1
  become: true
  tasks:
    - name: Copy environment variables
      copy:
        src: '../../environment/{{ item }}'
        dest: '{{ working_directory }}/env'
        owner: root
        group: root
      loop:
        - .env
        - .env_test