-
  hosts: runner
  tasks:
    -
      name: Init runner
      include_tasks: '../tasks/{{ item }}.yml'
      loop:
        - node_install
        - golang_install
    -
      name: Copy env
      copy:
        src: '../../environment/.env_runner'
        dest: ~/.env_runner