-
  hosts: runner
  tasks:
    -
      name: Init runner
      include_tasks: '../tasks/{{ item }}.yml'
      loop:
        - runner_dependencies_install
        - node_install
        - golang_install