-
  hosts: runner
  tasks:
    -
      name: Init runner
      include_tasks: '../tasks/{{ item }}.yml'
      loop:
        - node_install
        - golang_install
    -
      name: Copy env
      copy:
        src: '../../environment/.env_runner'
        dest: ~/.env_runner
    - name: Create folders for releases
      file:
        path: ~/ansible
        state: directory
    -
      name: Copy deploy SSH keys
      copy:
        src: '../../../secrets/runner-key'
        dest: ~/ansible/
        owner: github
        mode: 0600
    -
      name: Copy ansible playbook
      copy:
        src: '../deploy/{{ item }}'
        dest: ~/ansible/
      loop:
        - deploy_run.yml
        - hosts