-
  hosts: prod
  become: true
  tasks:
    -
      name: Delete old artifact
      file:
        state: absent
        path: '{{ working_directory }}/{{ item }}'
      loop:
        - deploy
        - f-deploy
    -
      name: Copy backend artifact
      copy:
        src: '/home/ubuntu/app/prod/{{ item }}'
        dest: '{{ working_directory }}'
        owner: root
        group: root
      loop:
        - deploy.tar.gz
        - f-deploy.tar.gz
        - post_deploy_bg.sh
        - swap_release.sh
        - notification.sh
    -
      name: Execute post deploy
      command: 'bash {{ working_directory }}/post_deploy_bg.sh'