name: Deploy

concurrency: production

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cd backend && make build && cd ..
      - run: cd frontend && npm i && npm run build && cd ..
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [build]
    steps:
      - run: sh deploy.sh